version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  
  events_management:
    build: ./events_management
    ports:
      - "8001:5000"
    volumes:
      - ./data:/home/data
    environment:
      FLASK_DEBUG: True
    
  tickets_management:
    build: ./tickets_management
    ports:
      - "8002:5000"
    volumes:
      - ./data:/home/data
    environment:
      FLASK_DEBUG: True